# tell travis we need sudo priviledges
sudo: required

services:
  - docker

before_install:
  - docker build -t usamamali/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true usamamali/docker-react npm run test
