# tell travis we need sudo priviledges
sudo: required

services:
  - docker

before_install:
  - docker build -t usamamali/docker-react -f Dockerfile.dev .

script:
  - docker run usamamali/docker-react npm run test -- --coverage
